---
title: "BarbieAndKen"
author: "Tony Zhang"
date: "2024-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
library(RColorBrewer)


lilBarbMelNo12 <-read.csv("lilbarbie12hrs.csv")
lilKenMelNo12 <-read.csv("lilken12hrs.csv")
lilKenMelCy6 <-read.csv("lilmelanocyte6hrs.csv")



```

```{r}
lilBarbie12Rs = head(Barbie12,100)
lilKen12Rs = head(Ken12,100)

BarbieKenMeansTable = data.frame(X = lilBarbie12Rs$X, Barbie12MeanIntensity = lilBarbie12Rs$Mean.Intensity, Ken12MeanIntensity = lilKen12Rs$Mean.Intensity)

ggplot(BarbieKenMeansTable, aes(x = X)) +
  geom_line(aes(y = Barbie12MeanIntensity), color = "pink", linetype = "solid", size = 1) +
  geom_line(aes(y = Ken12MeanIntensity), color = "blue", linetype = "solid", size = 1) +
  labs(x = "X", y = "Mean Intensity") +
  theme_minimal()
```



```{r}

# Create histograms
ggplot(lilBarbie12, aes(x = Mean.Intensity)) +
  geom_histogram(binwidth = 25, fill = "pink", color = "black", alpha = 0.7) +
  labs(x = "Mean Intensity", y = "Frequency") +
  theme_minimal()

# Create another histogram for Ken12MeanIntensity
ggplot(lilKen12, aes(x = Mean.Intensity)) +
  geom_histogram(binwidth = 25, fill = "blue", color = "black", alpha = 0.7) +
  labs(x = "Mean Intensity", y = "Frequency") +
  theme_minimal()
```

```{r}

ggplot() +
  geom_density(data = lilBarbMelNo12, aes(x = Mean.Intensity), color = "pink", size = 1) +
  geom_density(data = lilKenMelNo12, aes(x = Mean.Intensity), color = "blue", size = 1) +
  labs(x = "Mean Intensity") +
  theme_minimal()
```

```{r}
ggplot() +
  geom_density(data = lilBarbMelNo12, aes(x = Speed, color = "Barbie Melanoma"), size = 1) +
  geom_density(data = lilKenMelNo12, aes(x = Speed, color = "Ken Melanoma"), size = 1) +
  #geom_density(data = lilBarbMelCy6, aes(x = Mean.Speed, color = "Barbie Melanocyte"), size = 1) +
  geom_density(data = lilKenMelCy6, aes(x = Mean.Speed, color = "Ken Melanocyte"), size = 1) +
  labs(x = "Speed") +
  scale_color_manual(name = "Groups", values = c("Barbie Melanoma" = "pink", "Ken Melanoma" = "blue", "Barbie Melanocyte" = "red", "Ken Melanocyte" = "purple")) +
  theme_minimal()

```
```{r}
ggplot() +
  geom_density(data = lilBarbMelNo12, aes(x = Track.Length, color = "Barbie Melanoma"), size = 1) +
  geom_density(data = lilKenMelNo12, aes(x = Track.Length, color = "Ken Melanoma"), size = 1) +
  #geom_density(data = lilBarbMelCy6, aes(x = Track.Length, color = "Barbie Melanocyte"), size = 1) +
  geom_density(data = lilKenMelCy6, aes(x = Track.Length, color = "Ken Melanocyte"), size = 1) +
  labs(x = "Distance") +
  scale_color_manual(name = "Groups", values = c("Barbie Melanoma" = "pink", "Ken Melanoma" = "blue", "Barbie Melanocyte" = "red", "Ken Melanocyte" = "purple")) +
  theme_minimal()

```


```{r}
#numBarbMC = nrow(lilBarbMelCy6)
numBarbML = nrow(lilBarbMelNo12)
numKenMC = nrow(lilKenMelCy6)
numKenML = nrow(lilKenMelNo12)
data <- data.frame(Category = c("Barbie Melanoma", "Ken Melanocyte", "Ken Melanoma"),
                   Count = c(numBarbML, numKenMC, numKenML))


ggplot(data, aes(x = Category, y = Count, fill = Category)) +
  geom_bar(stat = "identity") +
  labs(x = "Cell Type", y = "Number of Cells", title = "Histogram of Number of Cells") +
  theme_minimal()
```
```{r}
ggplot() +
  geom_density(data = lilBarbMelNo12, aes(x = Duration, color = "Barbie Melanoma"), size = 1) +
  geom_density(data = lilKenMelNo12, aes(x = Duration, color = "Ken Melanoma"), size = 1) +
  #geom_density(data = lilBarbMelCy6, aes(x = Track.Length, color = "Barbie Melanocyte"), size = 1) +
  geom_density(data = lilKenMelCy6, aes(x = Duration, color = "Ken Melanocyte"), size = 1) +
  labs(x = "Duration") +
  scale_color_manual(name = "Groups", values = c("Barbie Melanoma" = "pink", "Ken Melanoma" = "blue", "Barbie Melanocyte" = "red", "Ken Melanocyte" = "purple")) +
  theme_minimal()

```
```{r}
ggplot() +
  stat_ecdf(data = lilKenMelNo12, aes(x = Duration, color = "Melanoma Duration"), size = 1) +
  stat_ecdf(data = lilKenMelCy6, aes(x = Duration, color = "Melanocyte Duration"), size = 1) +
  #stat_ecdf(data = lilKenMelNo12, aes(x = Mean.Intensity, color = "Melanoma Intensity"), size = 1) +
  #stat_ecdf(data = lilKenMelCy6, aes(x = Mean.Intensity, color = "Melanocyte Intensity"), size = 1) +
  #stat_ecdf(data = lilKenMelNo12, aes(x = Track.Length, color = "Melanoma Track Length"), size = 1) +
  #stat_ecdf(data = lilKenMelCy6, aes(x = Track.Length, color = "Melanocyte Track Length"), size = 1) +
  labs(x = "Duration") +
  scale_color_manual(name = "Groups", values = c("Melanoma Duration" = "red", "Melanocyte Duration" = "blue", "Melanoma Intensity" = "pink", "Melanocyte Intensity" = "purple", "Melanoma Track Length" = "aquamarine2", "Melanocyte Track Length" = "darkgoldenrod3")) +
  theme_minimal() +
  ggtitle("Empirical CDF of Duration")

```

```{r}
ggplot() +
  stat_ecdf(data = lilKenMelNo12, aes(x = Duration, color = "Ken Melanoma Duration"), size = 1) +
  stat_ecdf(data = lilBarbMelNo12, aes(x = Duration, color = "Barbie Melanoma Duration"), size = 1) +
  #stat_ecdf(data = lilKenMelNo12, aes(x = Mean.Intensity, color = "Ken Melanoma Intensity"), size = 1) +
  #stat_ecdf(data = lilBarbMelNo12, aes(x = Mean.Intensity, color = "Barbie Melanoma Intensity"), size = 1) +
  stat_ecdf(data = lilKenMelNo12, aes(x = Track.Length, color = "Ken Melanoma Track Length"), size = 1) +
  stat_ecdf(data = lilBarbMelNo12, aes(x = Track.Length, color = "Barbie Melanoma Track Length"), size = 1) +
  labs(x = "Track Length/Duration") +
  scale_color_manual(name = "Groups", values = c("Ken Melanoma Duration" = "red", "Barbie Melanoma Duration" = "blue", "Ken Melanoma Intensity" = "pink", "Barbie Melanoma Intensity" = "purple", "Ken Melanoma Track Length" = "aquamarine2", "Barbie Melanoma Track Length" = "darkgoldenrod3")) +
  theme_minimal() +
  ggtitle("Empirical CDF of Track Length and Duration")

```